// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Mysql = require("bs-mysql/src/Mysql.bs.js");

var conn = Mysql.createConnection("127.0.0.1", 3306, "ojisan", "ojisan", undefined, /* () */0);

Mysql.query(conn, "SHOW DATABASES", (function (result) {
        if (result.tag) {
          console.log(result[0].message);
          return /* () */0;
        } else {
          console.log(result[0].results);
          return /* () */0;
        }
      }));

conn.end();

exports.conn = conn;
/* conn Not a pure module */
